[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
cache_path = "cache/forge"
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=node_modules/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_price = 20_000_000_000 # 20 gwei

# Fuzzing settings
fuzz = { runs = 256 }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/demo"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
polygon = "https://polygon-rpc.com"
amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
